name: Build and Publish Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 11.x
        uses: actions/setup-node@master
        with:
          node-version: 11.x

      - name: Install dependencies # Install all deps
        run: yarn

      - name: Sync versions # Sync versions
        run: yarn syncprojects

      - name: Build ngx-scrolltop # Build
        run: yarn build

      - name: Build Schematics # Build Schematics and move
        run: yarn build:schematics

      - name: Publish docs
        run: git checkout gh-pages && git reset --hard origin/master && git push gh-pages --force && yarn deploy:ghpages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - name: Publish to GPR
        run: npm publish --registry=https://npm.pkg.github.com/@bartholomej --folder=dist/ngx-scrolltop
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - name: Publish
        uses: actions/npm@master
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        with:
          args: publish --folder dist/ngx-scrolltop
